language: node_js
node_js:
        - "8"
branches:
  only:
    - master

cache:
    directories:
        - "bower_components"

install:
  - npm install -g bower
  - npm install -g polymer-cli --unsafe-perm

before_script:
    - openssl aes-256-cbc -a -d -in key.pem.enc -out key.pem -k $ENC_KEY

script:
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./deploy.sh;'