language: node_js
node_js:
        - "8"
branches:
  only:
    - build

branches:
  except:
    - master

cache:
    directories:
        - "bower_components"

install:
  - npm install -g polymer-cli

script:
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./deploy.sh; fi'